[package]

name = "main_game"
version = "0.0.1"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies.game_logic]
path = "./game_logic"

[dependencies.game_input]
path = "./game_input"

[dependencies.game_window]
path = "./game_window"

[dependencies.game_gfx]
path = "./game_gfx"

