[package]

name = "game_logic"
version = "0.0.1"
authors = ["Alex McArther <acmcarther@gmail.com>"]

[dependencies]
time = "0.1.19"

[dependencies.shared_types]
path = "./../shared_types"

[dependencies.menus]
path = "./../menus"

